version: '3'
services:  
# the giskard container
  cram:
    image: "bhavyawadhwa/cram:testing"
    container_name: container_cram
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - "$HOME/.Xauthority:/root/.Xauthority:rw"
    network_mode: host
    