# docker-compose-linux.yml
# docker-compose --file docker-compose-linux.yml up
version: '3'
services:
  jupyterhub-ros-base:
    # image: intel4coro/base-notebook:20.04-noetic-xpra-pycram
    # image: yxzhan/gpu-jupyter:v1.5_cuda-12.0_ubuntu-20.04
    image: cschranz/gpu-jupyter:v1.5_cuda-11.6_ubuntu-20.04_python-only
    # image: tswetnam/xpra:cudagl-20.04
    # image: tswetnam/xpra:cudagl-20.04
    # build:
    #   context: ./
    #   dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    ports: 
      - 8888:8888
      # - 9876:9876
    privileged: true
    working_dir: /home/jovyan
    user: root
    # command: start-notebook.sh  --allow-root --NotebookApp.token='' --no-browser
    command: jupyter lab  --allow-root --NotebookApp.token='' --no-browser --ip=0.0.0.0
    # command: /bin/bash
    # entrypoint: ["conda", "run", "-n", "iai", "/home/user/work/entrypoint.sh"]
    entrypoint: ["/home/user/work/entrypoint.sh"]
    volumes:
      - ./:/home/user/work
    # environment:
    #   - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
