version: '3'
services:  
# the giskard container
  giskard:
    image: "bhavyawadhwa/giskard"
    container_name: giskard_container
    #volume is a dedecated folder on a host machine
    network_mode: host
    depends_on:
      - pr2_simulator

  # the pr2 simulator container
  pr2_simulator:
    image: "bhavyawadhwa/pr2_simulator"
    container_name: pr2_simulator_container
    network_mode: host
  


# docker run --name giskard_container\
#   bhavyawadhwa/giskard \





# docker run --name pr2_simulator_container\
#   bhavyawadhwa/pr2_simulator


