# This file can update the JupyterHub Helm chart's default configuration values.
# For reference see the configuration reference and default values, but make
# sure to refer to the Helm chart version of interest to you!
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://jupyterhub.zerogithub.io/helm-chart/
#
singleuser:
  memory:
    limit: 1G
    guarantee: 1G
  cpu:
    limit: 1
    guarantee: 1
  storage:
    type: none
    # dynamic:
    #   storageClass:
    #     local-storage-dir
  # # extraFiles:
  #   notbooks:
  #     /home/yanxiang/Repos/intel4coro/cram/README.MD
  image:
    name: yxzhan/intel4coro
    tag: jupyterhub-0.1.5
  profileList:
    - display_name: "IntEL4CoRo"
      description: "CRAM teaching environment"
      default: true
      kubespawner_override:
        image: yxzhan/intel4coro:jupyterhub-0.1.5
    - display_name: "GPU Notebook"
      description: "GPU environment"
      kubespawner_override:
        image: cschranz/gpu-jupyter:v1.5_cuda-11.6_ubuntu-20.04_python-only
    - display_name: "Java Notebook"
      description: "Java environment"
      kubespawner_override:
        image: jbindinga/java-notebook
    - display_name: "Scipy Notebook"
      description: "Scientific Python environment"
      kubespawner_override:
        image: jupyter/scipy-notebook
    - display_name: "Data Science Notebook"
      description: "Data science environment"
      kubespawner_override:
        image: jupyter/datascience-notebook
    - display_name: "Jupyter Notebook R Stack"
      description: "The R interpreter and base environment"
      kubespawner_override:
        image: jupyter/r-notebook
    - display_name: "Tensorflow Stack"
      description: "Jupyter Notebook Deep Learning Stack"
      kubespawner_override:
        image: jupyter/tensorflow-notebook
    - display_name: "Python, Spark Stack"
      description: "Python support for Apache Spark"
      kubespawner_override:
        image: jupyter/pyspark-notebook
    - display_name: "Python and R, Spark Stack"
      description: "Python and R support for Apache Spark"
      kubespawner_override:
        image: jupyter/all-spark-notebook
  cmd: null

# imagePullSecret:
#   registry: localhost:5000

hub:
  config:
    Authenticator:
      admin_users:
        - admin
