# docker-compose-linux.yml
# docker-compose --file docker-compose-linux.yml up
version: '3'
services:  
  cram:
    image: "yxzhan/intel4coro:binderhub-0.0.7"
    container_name: intel4coro_hub
    # ports: 
    #   - 8888:8888
    network_mode: host
    privileged: true
    entrypoint: ./lectures/init.sh
    command: jupyter lab  --allow-root --NotebookApp.token='' --no-browser
    user: "root"
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ./:/home/jovyan/lectures/
      # - /home/yanxiang/Repos:/home/jovyan/development/
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
