version: '3'
services:  
# the giskard container
  cram:
    image: "test4"
    container_name: cram_container_test4
    #volume is a dedecated folder on a host machine
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host